package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ChaosBudgetSpec defines the desired state of ChaosBudget
type ChaosBudgetSpec struct {
	Target   TargetSelector `json:"target"`
	Budget   BudgetSpec     `json:"budget"`
	Window   string         `json:"window"` // e.g. "1h"
	Policies []Policy       `json:"policies"`
}

type TargetSelector struct {
	Namespace string            `json:"namespace"`
	Labels    map[string]string `json:"labels"`
}

type BudgetSpec struct {
	Type string  `json:"type"` // "error-rate", "latency", "availability"
	Max  float64 `json:"max"`  // e.g. 0.05
}

type Policy struct {
	Type string `json:"type"` // "deny", "throttle", "noop"
}

// ChaosBudgetStatus defines the observed state of ChaosBudget
type ChaosBudgetStatus struct {
	Consumed    float64     `json:"consumed"`
	Remaining   float64     `json:"remaining"`
	LastUpdated metav1.Time `json:"lastUpdated"`
	Allowed     bool        `json:"allowed"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// ChaosBudget is the Schema for the chaosbudgets API
type ChaosBudget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ChaosBudgetSpec   `json:"spec,omitempty"`
	Status ChaosBudgetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ChaosBudgetList contains a list of ChaosBudget
type ChaosBudgetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ChaosBudget `json:"items"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosBudget) DeepCopyInto(out *ChaosBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosBudget.
func (in *ChaosBudget) DeepCopy() *ChaosBudget {
	if in == nil {
		return nil
	}
	out := new(ChaosBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosBudgetList) DeepCopyInto(out *ChaosBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosBudgetList.
func (in *ChaosBudgetList) DeepCopy() *ChaosBudgetList {
	if in == nil {
		return nil
	}
	out := new(ChaosBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosBudgetStatus) DeepCopyInto(out *ChaosBudgetStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

func init() {
	SchemeBuilder.Register(func(scheme *runtime.Scheme) error {
		scheme.AddKnownTypes(GroupVersion, &ChaosBudget{}, &ChaosBudgetList{})
		metav1.AddToGroupVersion(scheme, GroupVersion)
		return nil
	})
}
